<h1 style='color:blue;' align='center'>KFold Cross Validation Python - Exercise</h2>

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [2]:
iris = load_iris()

<h2 style='color:purple'>KFold cross validation</h2>

**Logistic regression model performance using cross_val_score**

In [5]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target, cv=3)
l_scores

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.97368421, 0.97368421, 0.94594595, 1.        ])

In [6]:
np.average(l_scores)

0.9733285917496444

**SVM model performance using cross_val_score**

In [7]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [8]:
np.average(s_scores)

0.9666666666666666

**Decision Tree performance using cross_val_score**

In [9]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [10]:
np.average(d_scores)

0.9666666666666668

**random forest performance using cross_val_score**


In [11]:
# We can fine tune params like n_estimators
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [12]:
np.average(r_scores)

0.96

cross_val_score uses stratifield kfold by default